[template]
name = "nocast-plugin"
cargo_generate_version = ">=0.10.0

[placeholders.license]
type = "string"
prompt = "License"
default = "MIT"

[placeholders.author]
type = "string"
prompt = "Author"
