[template]
name = "nocast-plugin"
description = "A template for creating plugins for nocast."

[placeholders]
project-name = {type = "string", prompt = "Plugin name?", default = "awesome-plugin"}
author = {type = "string", prompt = "Plugin author/developer?", default = "Darth Vader"}
license = {type = "string", prompt = "License for plugin (must be open-source)?", default = "MIT"}
